// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void demoTestIDE() {
    driver.get("https://www.ibu.edu.ba/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".menu__elem:nth-child(1) circle")).click();
    driver.findElement(By.cssSelector(".link__menu:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".menu__link:nth-child(1) > span")).click();
    driver.findElement(By.linkText("Information Technology")).click();
    js.executeScript("window.scrollTo(0,430.3999938964844)");
    js.executeScript("window.scrollTo(0,472)");
    js.executeScript("window.scrollTo(0,7175.2001953125)");
    js.executeScript("window.scrollTo(0,7734.39990234375)");
    js.executeScript("window.scrollTo(0,8232.7998046875)");
    js.executeScript("window.scrollTo(0,8410.400390625)");
    driver.findElement(By.cssSelector(".input")).click();
    driver.findElement(By.cssSelector(".input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".input"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".input")).sendKeys("hehe@me.com");
    driver.findElement(By.cssSelector(".btn__gold svg")).click();
    driver.close();
  }
}
